# Use a stable Java 17 version (Java 8 is outdated)
FROM openjdk:17
WORKDIR /app

# Copy the JAR file from target folder
COPY target/GestionClasses-0.0.1-SNAPSHOT.jar app.jar

# Expose the correct application port
EXPOSE 8088

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
